var UMKM_DATA = [
  {
    "nama_usaha": "Percetakan Qiana Konveksi dan Sablon",
    "pemilik": "Jasnawiah",
    "gender": "Perempuan",
    "alamat": "Jl. Mawar, Majjelling Wattang, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan",
    "maps": "Percetakan Qiana",
    "jenis_usaha": "Percetakan dan Konveksi",
    "produk": "Baju",
    "tahun_berdiri": "2023",
    "tenaga_kerja": "2–5 orang",
    "omzet": "Rp1.000.000–Rp5.000.000",
    "legalitas_narasi": "Berdasarkan data yang tersedia, usaha ini telah memiliki Nomor Induk Berusaha (NIB) dan merek dagang, namun belum memiliki Nomor Pokok Wajib Pajak (NPWP). Kondisi tersebut menunjukkan bahwa aspek legalitas usaha masih perlu dilengkapi agar operasional usaha memiliki dasar administratif yang lebih tertib dan memadai.",
    "pemasaran_narasi": "Pemasaran usaha dilakukan melalui penjualan langsung di toko maupun dari rumah, serta didukung oleh penggunaan WhatsApp sebagai media komunikasi dan promosi. Strategi ini menunjukkan bahwa usaha telah memanfaatkan kanal digital sederhana untuk menjangkau konsumen secara lebih luas.",
    "kondisi_narasi": "Kendala utama yang dihadapi berkaitan dengan aspek legalitas, khususnya NPWP, serta keterbatasan sumber daya manusia. Untuk mendukung pengembangan usaha, pemilik mengajukan kebutuhan bantuan permodalan. Dukungan tersebut diharapkan dapat memperkuat kapasitas usaha dan mendorong pertumbuhan yang lebih berkelanjutan.",
    "legalitas_dimiliki": [
      "Merek Dagang",
      "NIB"
    ],
    "legalitas_belum": [
      "NPWP"
    ],
    "legalitas_status": "sebagian",
    "kategori": "Kerajinan",
    "lingkungan": "Lingkungan 1",
    "tahun_berdiri_num": 2023,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Percetakan+Qiana+Majjelling+Wattang+Sidrap",
    "omzet_display": "Rp1.000.000 – Rp5.000.000",
    "omzet_kategori": "Rp1.000.000 – Rp5.000.000"
  },
  {
    "nama_usaha": "Toko Surianti",
    "pemilik": "Surianti",
    "gender": "Perempuan",
    "alamat": "Jl. Melati, Majjelling Wattang, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan, Lorong Masuk Gudang Cahaya Nabila",
    "maps": "Warung Surianti",
    "jenis_usaha": "Perdagangan",
    "produk": "Campuran",
    "tahun_berdiri": "2012",
    "tenaga_kerja": "1 orang",
    "omzet": "Rp1.000.000–Rp5.000.000",
    "legalitas_narasi": "Usaha ini belum memiliki NIB, merek dagang, maupun NPWP. Kondisi tersebut menunjukkan bahwa pemenuhan legalitas formal masih menjadi kebutuhan penting agar usaha memiliki landasan administrasi yang lebih kuat dan lebih siap untuk berkembang.",
    "pemasaran_narasi": "Pemasaran dilakukan melalui penjualan di toko dan dari rumah. Hingga saat ini, usaha belum menggunakan media digital dalam aktivitas promosi maupun penjualan. Dengan demikian, pola pemasaran masih bersifat konvensional dan masih memiliki peluang untuk diperluas melalui media digital.",
    "kondisi_narasi": "Kendala utama yang dihadapi adalah keterbatasan modal serta belum terpenuhinya aspek legalitas usaha. Pelaku usaha menyatakan belum memiliki kebutuhan pengembangan usaha secara khusus. Meskipun demikian, penguatan pada aspek modal dan legalitas tetap relevan untuk mendukung keberlanjutan usaha di masa mendatang.",
    "legalitas_dimiliki": [],
    "legalitas_belum": [
      "Merek Dagang",
      "NIB",
      "NPWP"
    ],
    "legalitas_status": "belum",
    "kategori": "Perdagangan",
    "lingkungan": "Lingkungan 1",
    "tahun_berdiri_num": 2012,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Warung+Surianti+Majjelling+Wattang+Sidrap",
    "omzet_display": "Rp1.000.000 – Rp5.000.000",
    "omzet_kategori": "Rp1.000.000 – Rp5.000.000"
  },
  {
    "nama_usaha": "Samosa-Na Sidenreng",
    "pemilik": "Hj. Mini",
    "gender": "Perempuan",
    "alamat": "Jl. Ganggawa, Majjelling Wattang, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan",
    "maps": "-",
    "jenis_usaha": "Kuliner",
    "produk": "Samosa dan Risoles",
    "tahun_berdiri": "2022/2023",
    "tenaga_kerja": "2–5 orang",
    "omzet": "Rp5.000.001–Rp10.000.000.",
    "legalitas_narasi": "Usaha ini belum memiliki PIRT, merek dagang, maupun NPWP. Kondisi tersebut menunjukkan bahwa aspek legalitas masih perlu menjadi perhatian utama agar usaha memiliki dasar hukum yang lebih kuat dan siap berkembang secara formal.",
    "pemasaran_narasi": "Pemasaran dilakukan melalui toko, dari rumah, dan secara online. Media digital yang digunakan adalah WhatsApp. Pola ini menunjukkan bahwa usaha telah memiliki jangkauan pemasaran yang lebih fleksibel melalui perpaduan metode konvensional dan digital.",
    "kondisi_narasi": "Kendala utama yang dihadapi adalah kebutuhan tambahan tenaga kerja pada waktu tertentu. Untuk pengembangan usaha, pelaku usaha mengharapkan pelatihan digital marketing serta sertifikat halal. Kebutuhan tersebut dinilai penting untuk memperkuat daya saing dan meningkatkan kepercayaan konsumen.",
    "legalitas_dimiliki": [
      "NIB",
      "Sertifikat Halal"
    ],
    "legalitas_belum": [
      "Merek Dagang",
      "NPWP",
      "PIRT"
    ],
    "legalitas_status": "sebagian",
    "kategori": "Kuliner",
    "lingkungan": "Lingkungan 1",
    "tahun_berdiri_num": 2022,
    "maps_url": "https://maps.app.goo.gl/gNQtgN9qm5chZ2Ny8?g_st=ac",
    "omzet_display": "Rp5.000.001 – Rp10.000.000",
    "omzet_kategori": "Rp5.000.000 – Rp10.000.000"
  },
  {
    "nama_usaha": "Toko Hijrah",
    "pemilik": "Hijrah",
    "gender": "Perempuan",
    "alamat": "Jl. Veteran, Majjelling Wattang, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan",
    "maps": "Tk Hijrah",
    "jenis_usaha": "Perdagangan",
    "produk": "Campuran",
    "tahun_berdiri": "2024",
    "tenaga_kerja": "2–5 orang",
    "omzet": "Rp1.000.000–Rp5.000.000.",
    "legalitas_narasi": "Berdasarkan data yang tersedia, usaha ini telah memiliki NIB, namun belum memiliki merek dagang dan NPWP. Kondisi tersebut menunjukkan bahwa pemenuhan aspek legalitas masih perlu ditingkatkan agar usaha memiliki dasar administratif yang lebih kuat dan lebih tertata.",
    "pemasaran_narasi": "Pemasaran dilakukan melalui penjualan di toko dan dari rumah. Hingga saat ini, usaha belum menggunakan media digital sebagai sarana promosi. Dengan demikian, pemasaran masih bersifat konvensional dan masih terbuka peluang untuk dikembangkan melalui pemanfaatan media digital.",
    "kondisi_narasi": "Kendala utama yang dihadapi adalah kenaikan harga barang jualan. Untuk pengembangan usaha, pemilik mengharapkan pendampingan OSS/NIB. Kebutuhan tersebut dinilai penting untuk mendukung penguatan legalitas dan keberlanjutan usaha.",
    "legalitas_dimiliki": [
      "NIB"
    ],
    "legalitas_belum": [
      "Merek Dagang",
      "NPWP"
    ],
    "legalitas_status": "sebagian",
    "kategori": "Perdagangan",
    "lingkungan": "Lingkungan 1",
    "tahun_berdiri_num": 2024,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Tk+Hijrah+Majjelling+Wattang+Sidrap",
    "omzet_display": "Rp1.000.000 – Rp5.000.000",
    "omzet_kategori": "Rp1.000.000 – Rp5.000.000"
  },
  {
    "nama_usaha": "Pempek Mak Ifah",
    "pemilik": "Syarifah",
    "gender": "Perempuan",
    "alamat": "Jl. Ganggawa, Majjelling Wattang, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan",
    "maps": "Pempek Mak Ifah",
    "jenis_usaha": "Kuliner",
    "produk": "Pempek",
    "tahun_berdiri": "2020",
    "tenaga_kerja": "2–5 orang",
    "omzet": "kurang dari Rp1.000.000.",
    "legalitas_narasi": "Usaha ini belum memiliki PIRT, merek dagang, maupun NPWP. Kondisi tersebut menunjukkan bahwa aspek legalitas masih menjadi hal yang perlu dibenahi agar usaha lebih siap berkembang secara formal dan memiliki kepercayaan yang lebih kuat dari konsumen.",
    "pemasaran_narasi": "Pemasaran dilakukan melalui penjualan di toko, dari rumah, menitipkan produk di warung, serta melalui penjualan online. Media digital yang digunakan meliputi WhatsApp, Facebook, dan Instagram. Pola pemasaran ini menunjukkan bahwa usaha telah memanfaatkan saluran promosi yang cukup beragam untuk menjangkau konsumen.",
    "kondisi_narasi": "Kendala utama yang dihadapi adalah pemasaran. Untuk pengembangan usaha, pelaku usaha membutuhkan penguatan pada aspek branding produk. Kebutuhan ini relevan untuk memperkuat identitas produk dan meningkatkan daya saing di pasar.",
    "legalitas_dimiliki": [
      "NIB",
      "Sertifikat Halal"
    ],
    "legalitas_belum": [
      "Merek Dagang",
      "NPWP",
      "PIRT"
    ],
    "legalitas_status": "sebagian",
    "kategori": "Kuliner",
    "lingkungan": "Lingkungan 1",
    "tahun_berdiri_num": 2020,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Pempek+Mak+Ifah+Majjelling+Wattang+Sidrap",
    "omzet_display": "kurang dari Rp1.000.000",
    "omzet_kategori": "< Rp1.000.000"
  },
  {
    "nama_usaha": "Lia Cake",
    "pemilik": "Liawati",
    "gender": "Perempuan",
    "alamat": "Jl. Ganggawa, Majjelling Wattang, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan, belakang Kedai Firdah",
    "maps": "-",
    "jenis_usaha": "Kuliner",
    "produk": "Aneka Kue (Donat, Panada, Risoles, Roti Goreng, dan Roti Basah)",
    "tahun_berdiri": "2012",
    "tenaga_kerja": "1 orang",
    "omzet": "Rp1.000.000–Rp5.000.000",
    "legalitas_narasi": "Berdasarkan data yang tersedia, usaha ini belum memiliki PIRT, merek dagang, maupun NPWP. Kondisi tersebut menunjukkan bahwa legalitas usaha masih perlu dilengkapi agar kegiatan usaha memiliki landasan administratif yang lebih memadai.",
    "pemasaran_narasi": "Pemasaran dilakukan melalui penjualan di toko, dari rumah, serta menitipkan produk di warung. Media digital yang digunakan adalah WhatsApp. Pola ini memperlihatkan adanya kombinasi pemasaran langsung dan sederhana berbasis digital.",
    "kondisi_narasi": "Kendala utama yang dihadapi meliputi modal, peralatan produksi, dan legalitas usaha. Untuk pengembangan usaha, pelaku usaha membutuhkan pendampingan OSS/NIB, sertifikasi halal, serta bantuan permodalan. Dukungan tersebut diharapkan dapat memperkuat kapasitas produksi dan memperluas jangkauan usaha.",
    "legalitas_dimiliki": [
      "NIB",
      "Sertifikat Halal"
    ],
    "legalitas_belum": [
      "Merek Dagang",
      "NPWP",
      "PIRT"
    ],
    "legalitas_status": "sebagian",
    "kategori": "Kuliner",
    "lingkungan": "Lingkungan 1",
    "tahun_berdiri_num": 2012,
    "maps_url": "https://maps.app.goo.gl/AqoNrAgFiEhocSoZ8?g_st=ac",
    "omzet_display": "Rp1.000.000 – Rp5.000.000",
    "omzet_kategori": "Rp1.000.000 – Rp5.000.000"
  },
  {
    "nama_usaha": "Kios Dafa Dafin",
    "pemilik": "Supriadi",
    "gender": "Laki-laki",
    "alamat": "Jl. Anggrek, MajjellinG Wattang, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan",
    "maps": "Kedai Hijrah",
    "jenis_usaha": "Perdagangan",
    "produk": "Campuran",
    "tahun_berdiri": "2025",
    "tenaga_kerja": "1 orang",
    "omzet": "Rp1.000.000–Rp5.000.000",
    "legalitas_narasi": "Data menunjukkan bahwa usaha ini belum memiliki NIB, merek dagang, maupun NPWP. Kondisi ini menandakan perlunya penguatan aspek legalitas agar usaha memiliki kejelasan administrasi dan lebih siap untuk berkembang di masa mendatang.",
    "pemasaran_narasi": "Pemasaran dilakukan melalui penjualan di toko dan dari rumah. Usaha ini tidak menggunakan media digital dalam aktivitas pemasarannya. Oleh karena itu, pola pemasaran masih sangat bergantung pada penjualan langsung dan belum memanfaatkan saluran digital.",
    "kondisi_narasi": "Kendala utama yang dihadapi adalah keengganan untuk mengembangkan usaha karena faktor usia. Adapun kebutuhan pengembangan usaha juga dinyatakan sama, yaitu tidak terdapat rencana pengembangan lebih lanjut. Kondisi ini menunjukkan bahwa usaha cenderung dipertahankan dalam skala yang ada saat ini.",
    "legalitas_dimiliki": [],
    "legalitas_belum": [
      "Merek Dagang",
      "NIB",
      "NPWP"
    ],
    "legalitas_status": "belum",
    "kategori": "Perdagangan",
    "lingkungan": "Lingkungan 1",
    "tahun_berdiri_num": 2025,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Kedai+Hijrah+Majjelling+Wattang+Sidrap",
    "omzet_display": "Rp1.000.000 – Rp5.000.000",
    "omzet_kategori": "Rp1.000.000 – Rp5.000.000"
  },
  {
    "nama_usaha": "Dapoer Qiana Mini ATM",
    "pemilik": "Niar",
    "gender": "Perempuan",
    "alamat": "Jl. Anggrek, Majjelling Wattang, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan",
    "maps": "Dapoer Qiana",
    "jenis_usaha": "Minuman dan jasa",
    "produk": "Es teh dan Transaksi",
    "tahun_berdiri": "2024",
    "tenaga_kerja": "2–5 orang",
    "omzet": "kurang dari Rp1.000.000",
    "legalitas_narasi": "Berdasarkan data yang tersedia, usaha ini belum memiliki PIRT, merek dagang, maupun NPWP. Kondisi tersebut menunjukkan bahwa aspek legalitas masih perlu menjadi perhatian utama agar usaha memiliki fondasi administratif yang lebih kuat.",
    "pemasaran_narasi": "Pemasaran dilakukan melalui penjualan di toko dan dari rumah, dengan dukungan WhatsApp sebagai media komunikasi. Strategi ini menunjukkan bahwa usaha memanfaatkan media sederhana untuk mendukung interaksi dengan pelanggan.",
    "kondisi_narasi": "Kendala utama yang dihadapi adalah legalitas usaha. Untuk pengembangan usaha, tidak terdapat kebutuhan khusus yang disampaikan. Meskipun demikian, pengurusan legalitas tetap dapat menjadi langkah penting bagi keberlanjutan usaha.",
    "legalitas_dimiliki": [
      "NIB",
      "Sertifikat Halal"
    ],
    "legalitas_belum": [
      "Merek Dagang",
      "NPWP",
      "PIRT"
    ],
    "legalitas_status": "sebagian",
    "kategori": "Jasa",
    "lingkungan": "Lingkungan 1",
    "tahun_berdiri_num": 2024,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Dapoer+Qiana+Majjelling+Wattang+Sidrap",
    "omzet_display": "kurang dari Rp1.000.000",
    "omzet_kategori": "< Rp1.000.000"
  },
  {
    "nama_usaha": "Toko Nuril",
    "pemilik": "Sartika",
    "gender": "Perempuan",
    "alamat": "Jl. Melati, Majjelling Wattang, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan",
    "maps": "-",
    "jenis_usaha": "Jajanan",
    "produk": "Sosis, Mie sumpit, Nugget, dan Minuman",
    "tahun_berdiri": "2025",
    "tenaga_kerja": "2–5 orang",
    "omzet": "kurang dari Rp1.000.000",
    "legalitas_narasi": "Usaha ini belum memiliki PIRT, merek dagang, maupun NPWP. Kondisi tersebut menunjukkan perlunya penguatan legalitas agar usaha memiliki ketertiban administrasi yang lebih baik.",
    "pemasaran_narasi": "Pemasaran dilakukan melalui penjualan di toko dan dari rumah. Saat ini, usaha belum menggunakan media digital. Dengan demikian, potensi pengembangan pemasaran melalui platform digital masih sangat terbuka.",
    "kondisi_narasi": "Kendala utama yang dihadapi adalah pemasaran. Untuk pengembangan usaha, pelaku usaha membutuhkan pendampingan OSS/NIB, sertifikasi halal, serta bantuan permodalan. Kebutuhan tersebut penting untuk memperkuat daya saing dan keberlangsungan usaha.",
    "legalitas_dimiliki": [
      "NIB",
      "Sertifikat Halal"
    ],
    "legalitas_belum": [
      "Merek Dagang",
      "NPWP",
      "PIRT"
    ],
    "legalitas_status": "sebagian",
    "kategori": "Kuliner",
    "lingkungan": "Lingkungan 1",
    "tahun_berdiri_num": 2025,
    "maps_url": "https://maps.app.goo.gl/YJ8GscaReQ9YRSe47?g_st=ac",
    "omzet_display": "kurang dari Rp1.000.000",
    "omzet_kategori": "< Rp1.000.000"
  },
  {
    "nama_usaha": "Toko Mutiah Mukti",
    "pemilik": "Hj. Masriani",
    "gender": "Perempuan",
    "alamat": "Jl. Melati, Majjelling Wattang, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan",
    "maps": "Toko Mutiah Mukti",
    "jenis_usaha": "Perdagangan",
    "produk": "Campuran",
    "tahun_berdiri": "2017",
    "tenaga_kerja": "2–5 orang",
    "omzet": "kurang dari Rp1.000.000",
    "legalitas_narasi": "Berdasarkan data yang tersedia, usaha ini telah memiliki NIB, merek dagang, dan NPWP. Kondisi ini menunjukkan bahwa aspek legalitas usaha sudah cukup lengkap dan menjadi modal penting bagi keberlangsungan usaha.",
    "pemasaran_narasi": "Pemasaran dilakukan melalui penjualan di toko, dari rumah, dan di pasar. Usaha ini tidak menggunakan media digital, sehingga aktivitas pemasaran masih bergantung pada cara konvensional.",
    "kondisi_narasi": "Kendala utama yang dihadapi adalah modal dan legalitas. Untuk pengembangan usaha, pelaku usaha membutuhkan pendampingan OSS/NIB serta bantuan permodalan. Kebutuhan tersebut penting untuk memperkuat struktur usaha dan mendukung perkembangan ke depan.",
    "legalitas_dimiliki": [
      "Merek Dagang",
      "NIB",
      "NPWP"
    ],
    "legalitas_belum": [
      "PIRT",
      "Sertifikat Halal"
    ],
    "legalitas_status": "sebagian",
    "kategori": "Perdagangan",
    "lingkungan": "Lingkungan 1",
    "tahun_berdiri_num": 2017,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Toko+Mutiah+Mukti+Majjelling+Wattang+Sidrap",
    "omzet_display": "kurang dari Rp1.000.000",
    "omzet_kategori": "< Rp1.000.000"
  },
  {
    "nama_usaha": "Toko Suci",
    "pemilik": "Rasyidin",
    "gender": "Laki-laki",
    "alamat": "Jl. Melati, Majjelling Wattang, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan, depan Masjid Al Husna",
    "maps": "-",
    "jenis_usaha": "Perdagangan",
    "produk": "Campuran",
    "tahun_berdiri": "2010",
    "tenaga_kerja": "2–5 orang",
    "omzet": "kurang dari Rp1.000.000",
    "legalitas_narasi": "Usaha ini baru memiliki NIB dan NPWP. Kondisi legalitas tersebut menunjukkan bahwa masih ada ruang untuk melengkapi dokumen usaha agar lebih kuat secara administratif.",
    "pemasaran_narasi": "Pemasaran dilakukan melalui penjualan di toko dan dari rumah. Usaha ini tidak menggunakan media digital. Dengan demikian, strategi pemasaran masih sepenuhnya mengandalkan pendekatan langsung kepada pelanggan.",
    "kondisi_narasi": "Kendala utama yang dihadapi meliputi modal, pemasaran, dan legalitas. Untuk pengembangan usaha, dibutuhkan pendampingan OSS/NIB serta bantuan permodalan. Dukungan tersebut dapat membantu memperbaiki aspek administratif sekaligus memperkuat kemampuan usaha dalam menjangkau pasar.",
    "legalitas_dimiliki": [
      "NIB",
      "NPWP"
    ],
    "legalitas_belum": [
      "PIRT",
      "Sertifikat Halal",
      "Merek Dagang"
    ],
    "legalitas_status": "sebagian",
    "kategori": "Perdagangan",
    "lingkungan": "Lingkungan 1",
    "tahun_berdiri_num": 2010,
    "maps_url": "https://maps.app.goo.gl/o1EMcgkzcK5r89Uw7?g_st=ac",
    "omzet_display": "kurang dari Rp1.000.000",
    "omzet_kategori": "< Rp1.000.000"
  },
  {
    "nama_usaha": "Alo Kopi",
    "pemilik": "Suratman",
    "gender": "Laki-laki",
    "alamat": "Jl. Anggrek, Majjelling Wattang, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan, depan Masjid Al-Husna",
    "maps": "Alo Kopi",
    "jenis_usaha": "Coffee shop",
    "produk": "Kopi",
    "tahun_berdiri": "2023",
    "tenaga_kerja": "1 orang",
    "omzet": "Rp1.000.000–Rp5.000.000",
    "legalitas_narasi": "Berdasarkan data yang tersedia, usaha ini telah memiliki NIB, sertifikat halal, PIRT, merek dagang, dan NPWP. Dengan kelengkapan legalitas tersebut, usaha ini memiliki dasar administratif yang cukup baik untuk mendukung keberlanjutan usahanya.",
    "pemasaran_narasi": "Pemasaran dilakukan melalui penjualan di toko dan dari rumah, serta secara online. Media digital yang digunakan adalah Instagram. Pola ini menunjukkan bahwa usaha telah memanfaatkan pemasaran digital untuk memperluas jangkauan pelanggan.",
    "kondisi_narasi": "Kendala utama yang dihadapi adalah modal, peralatan produksi, bahan baku, dan legalitas. Untuk pengembangan usaha, pelaku usaha membutuhkan pendampingan OSS/NIB serta dukungan terkait lokasi. Kebutuhan tersebut relevan untuk meningkatkan efisiensi operasional dan daya saing usaha.",
    "legalitas_dimiliki": [
      "Merek Dagang",
      "NIB",
      "NPWP",
      "PIRT",
      "Sertifikat Halal"
    ],
    "legalitas_belum": [],
    "legalitas_status": "lengkap",
    "kategori": "Kuliner",
    "lingkungan": "Lingkungan 1",
    "tahun_berdiri_num": 2023,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Alo+Kopi+Majjelling+Wattang+Sidrap",
    "omzet_display": "Rp1.000.000 – Rp5.000.000",
    "omzet_kategori": "Rp1.000.000 – Rp5.000.000"
  },
  {
    "nama_usaha": 'Depot Air Minum "Harun Water"',
    "pemilik": "Harman",
    "gender": "Laki-laki",
    "alamat": "Jl. Anggrek, Majjelling Wattang, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan",
    "maps": "Depot Air Minum Harun Water",
    "jenis_usaha": "Depot air minum",
    "produk": "Air Galon",
    "tahun_berdiri": "2018",
    "tenaga_kerja": "1 orang",
    "omzet": "Rp5.000.000–Rp10.000.000",
    "legalitas_narasi": "Usaha ini telah memiliki NIB, PIRT, merek dagang, dan NPWP, sementara sertifikat halal belum tercantum. Secara umum, legalitas usaha sudah cukup baik, meskipun masih ada aspek yang dapat dilengkapi",
    "pemasaran_narasi": "Pemasaran dilakukan melalui penjualan di toko dan dari rumah, dengan WhatsApp sebagai media digital. Strategi ini menunjukkan bahwa usaha mengandalkan komunikasi langsung dan pemasaran sederhana berbasis digital.",
    "kondisi_narasi": "Kendala utama yang dihadapi berkaitan dengan bahan baku dan kenaikan harga yang dirasakan serba mahal. Dalam uraian kendala, disebutkan bahwa kondisi ini sudah berlangsung sejak perang Irak-Amerika. Untuk saat ini, pelaku usaha menyatakan tidak ada kebutuhan pengembangan usaha.",
    "legalitas_dimiliki": [
      "Merek Dagang",
      "NIB",
      "NPWP",
      "PIRT"
    ],
    "legalitas_belum": [
      "Sertifikat Halal"
    ],
    "legalitas_status": "sebagian",
    "kategori": "Jasa",
    "lingkungan": "Lingkungan 1",
    "tahun_berdiri_num": 2018,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Depot+Air+Minum+Harun+Water+Majjelling+Wattang+Sidrap",
    "omzet_display": "Rp5.000.000 – Rp10.000.000",
    "omzet_kategori": "Rp5.000.000 – Rp10.000.000"
  },
  {
    "nama_usaha": "Nasi Goreng Mas Alfin",
    "pemilik": "Ilaluddin",
    "gender": "Laki-laki",
    "alamat": "Jl. Jendral Sudirman, Majjelling Wattang, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan",
    "maps": "Iam phone cell",
    "jenis_usaha": "Kuliner",
    "produk": "Nasi Goreng, Mie Kuah, Mie Goreng, dan Berbagai Jenis Gorengan",
    "tahun_berdiri": "2018",
    "tenaga_kerja": "2–5 orang",
    "omzet": "Rp1.000.000–Rp5.000.000",
    "legalitas_narasi": "Usaha ini telah memiliki NIB dan sertifikat halal, sedangkan PIRT, merek dagang, dan NPWP belum tercantum. Kondisi ini menunjukkan bahwa sebagian aspek legalitas sudah terpenuhi, namun masih ada ruang untuk penyempurnaan.",
    "pemasaran_narasi": "Pemasaran dilakukan melalui warung pinggir jalan. Media digital yang digunakan adalah WhatsApp. Pola ini memperlihatkan bahwa usaha memadukan penjualan langsung dengan komunikasi digital sederhana.",
    "kondisi_narasi": "Kendala utama yang dihadapi adalah bahan baku. Untuk pengembangan usaha, tidak ada kebutuhan khusus yang disampaikan. Dengan demikian, fokus utama saat ini tampaknya masih pada kestabilan pasokan bahan baku.",
    "legalitas_dimiliki": [
      "NIB",
      "Sertifikat Halal"
    ],
    "legalitas_belum": [
      "Merek Dagang",
      "NPWP",
      "PIRT"
    ],
    "legalitas_status": "sebagian",
    "kategori": "Kuliner",
    "lingkungan": "Lingkungan 1",
    "tahun_berdiri_num": 2018,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Iam+phone+cell+Majjelling+Wattang+Sidrap",
    "omzet_display": "Rp1.000.000 – Rp5.000.000",
    "omzet_kategori": "Rp1.000.000 – Rp5.000.000"
  },
  {
    "nama_usaha": "Dapur Mamud 17",
    "pemilik": "Milda",
    "gender": "Perempuan",
    "alamat": "Jl. Jendral Sudirman, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan",
    "maps": "-",
    "jenis_usaha": "Kuliner",
    "produk": "Makanan",
    "tahun_berdiri": "2015",
    "tenaga_kerja": "1 orang",
    "omzet": "Rp1.000.000–Rp5.000.000",
    "legalitas_narasi": "Usaha ini belum memiliki NIB, sertifikat halal, PIRT, merek dagang, maupun NPWP. Kondisi tersebut menunjukkan bahwa legalitas usaha masih perlu dilengkapi agar usaha lebih siap berkembang secara formal.",
    "pemasaran_narasi": "Pemasaran dilakukan melalui penjualan di toko dan dari rumah, serta secara online. Media digital yang digunakan adalah WhatsApp, Facebook, dan Instagram. Ini menunjukkan usaha cukup aktif memanfaatkan media sosial untuk promosi.",
    "kondisi_narasi": "Kendala utama yang dihadapi tidak ada. Untuk pengembangan usaha, dibutuhkan pendampingan OSS/NIB dan sertifikasi halal. Walaupun tidak ada kendala yang dirasakan, dukungan tersebut tetap penting untuk meningkatkan kesiapan usaha.",
    "legalitas_dimiliki": [],
    "legalitas_belum": [
      "Merek Dagang",
      "NIB",
      "NPWP",
      "PIRT",
      "Sertifikat Halal"
    ],
    "legalitas_status": "belum",
    "kategori": "Kuliner",
    "lingkungan": "Lingkungan 2",
    "tahun_berdiri_num": 2015,
    "maps_url": "https://maps.app.goo.gl/Zejdwbpt9ADZ253X7?g_st=ac",
    "omzet_display": "Rp1.000.000 – Rp5.000.000",
    "omzet_kategori": "Rp1.000.000 – Rp5.000.000"
  },
  {
    "nama_usaha": "Sweet Drink",
    "pemilik": "Nur Ismayani",
    "gender": "Perempuan",
    "alamat": "Jl. Jeendral Sudirman, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan",
    "maps": "-",
    "jenis_usaha": "Minuman",
    "produk": "Minuman (Berbagai macam rasa Pop Ice)",
    "tahun_berdiri": "2024",
    "tenaga_kerja": "1 orang",
    "omzet": "Rp1.000.000–Rp5.000.000",
    "legalitas_narasi": "Berdasarkan data yang tersedia, sebagian aspek legalitas yang dicantumkan masih belum terpenuhi, termasuk PIRT, merek dagang, dan NPWP. Kondisi ini menunjukkan bahwa usaha masih memerlukan penguatan administrative.",
    "pemasaran_narasi": "Pemasaran dilakukan melalui penjualan di toko dan dari rumah. Saat ini usaha belum menggunakan media digital. Hal ini menandakan bahwa pemasaran masih bergantung pada cara konvensional.",
    "kondisi_narasi": "Kendala utama yang dihadapi adalah pemasaran. Untuk pengembangan usaha, pemilik membutuhkan pendampingan media sosial. Kebutuhan ini relevan untuk membantu usaha menjangkau konsumen yang lebih luas.",
    "legalitas_dimiliki": [
      "NIB",
      "Sertifikat Halal"
    ],
    "legalitas_belum": [
      "NPWP",
      "PIRT",
      "Merek Dagang"
    ],
    "legalitas_status": "sebagian",
    "kategori": "Kuliner",
    "lingkungan": "Lingkungan 2",
    "tahun_berdiri_num": 2024,
    "maps_url": "https://maps.app.goo.gl/Zejdwbpt9ADZ253X7?g_st=ac",
    "omzet_display": "Rp1.000.000 – Rp5.000.000",
    "omzet_kategori": "Rp1.000.000 – Rp5.000.000"
  },
  {
    "nama_usaha": "Rumah Manisan A.R",
    "pemilik": "Ria",
    "gender": "Perempuan",
    "alamat": "Jl. Jendral Sudirman, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan",
    "maps": "-",
    "jenis_usaha": "Kuliner",
    "produk": "Manisan Mangga, Nanas, Salak, Kedondong, dan lain-lain",
    "tahun_berdiri": "2025",
    "tenaga_kerja": "1 orang",
    "omzet": "lebih dari Rp10.000.000",
    "legalitas_narasi": "Usaha ini belum memiliki NIB, sertifikat halal, PIRT, merek dagang, maupun NPWP. Dengan kondisi tersebut, legalitas usaha masih menjadi aspek yang perlu segera diperhatikan.",
    "pemasaran_narasi": "Penjualan dilakukan melalui toko, dari rumah, dan secara online. Media digital yang digunakan adalah WhatsApp, Facebook, dan Instagram. Pola ini menunjukkan usaha sudah memanfaatkan beberapa kanal digital untuk promosi.",
    "kondisi_narasi": "Kendala utama yang dihadapi adalah pemasaran. Untuk pengembangan usaha, diperlukan pendampingan OSS/NIB dan sertifikasi halal. Kedua hal ini dapat membantu memperkuat kepercayaan konsumen dan legalitas usaha.",
    "legalitas_dimiliki": [],
    "legalitas_belum": [
      "Merek Dagang",
      "NIB",
      "NPWP",
      "PIRT",
      "Sertifikat Halal"
    ],
    "legalitas_status": "belum",
    "kategori": "Kuliner",
    "lingkungan": "Lingkungan 2",
    "tahun_berdiri_num": 2025,
    "maps_url": "https://maps.app.goo.gl/duwqGvBS4Q9rE3iq8?g_st=ac",
    "omzet_display": "lebih dari Rp10.000.000",
    "omzet_kategori": "> Rp10.000.000"
  },
  {
    "nama_usaha": "Kedai Hatimah",
    "pemilik": "Hatimah",
    "gender": "Perempuan",
    "alamat": "Jl. Jendral Sudirman, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan",
    "maps": "-",
    "jenis_usaha": "Minuman",
    "produk": "Minuman",
    "tahun_berdiri": "2026",
    "tenaga_kerja": "1 orang",
    "omzet": "Rp1.000.000–Rp5.000.000",
    "legalitas_narasi": "Data menunjukkan bahwa usaha ini belum memiliki NIB, sertifikat halal, PIRT, merek dagang, maupun NPWP. Kondisi tersebut menandakan perlunya pembenahan legalitas agar usaha lebih siap berkembang.",
    "pemasaran_narasi": "Pemasaran dilakukan melalui penjualan di toko dan dari rumah. Media digital yang digunakan adalah WhatsApp dan Facebook. Artinya, usaha sudah mulai memanfaatkan media sosial meski masih sederhana.",
    "kondisi_narasi": "Kendala utama yang dihadapi adalah modal. Dalam uraian kendala disebutkan bahwa modal untuk membeli bahan baku kadang tidak cukup. Untuk pengembangan usaha, pemilik membutuhkan bantuan permodalan.",
    "legalitas_dimiliki": [],
    "legalitas_belum": [
      "Merek Dagang",
      "NIB",
      "NPWP",
      "PIRT",
      "Sertifikat Halal"
    ],
    "legalitas_status": "belum",
    "kategori": "Kuliner",
    "lingkungan": "Lingkungan 2",
    "tahun_berdiri_num": 2026,
    "maps_url": "https://maps.app.goo.gl/jdg9QMoxWNX6KY6R7?g_st=ac",
    "omzet_display": "Rp1.000.000 – Rp5.000.000",
    "omzet_kategori": "Rp1.000.000 – Rp5.000.000"
  },
  {
    "nama_usaha": "Kedai Ameera",
    "pemilik": "Satriani",
    "gender": "Perempuan",
    "alamat": "Jl. Jendal Sudirman, Maritengngae, Sidrap, Sulawesi Selatan",
    "maps": "Kedai Ameera",
    "jenis_usaha": "Kuliner",
    "produk": "Minuman dan Es Kulkul Buah",
    "tahun_berdiri": "2026",
    "tenaga_kerja": "1 orang",
    "omzet": "Rp1.000.000–Rp5.000.000",
    "legalitas_narasi": "Usaha ini belum memiliki PIRT, merek dagang, maupun NPWP. Dengan demikian, aspek legalitas masih perlu menjadi perhatian utama dalam pengembangan usaha.",
    "pemasaran_narasi": "Pemasaran dilakukan melalui penjualan di toko dan dari rumah. Media digital yang digunakan adalah WhatsApp. Strategi ini menunjukkan pemasaran masih sederhana namun sudah memakai komunikasi digital.",
    "kondisi_narasi": "Kendala utama yang dihadapi adalah bahan baku, karena bahan baku mulai mahal. Untuk pengembangan usaha, dibutuhkan pendampingan OSS/NIB dan sertifikasi halal. Dukungan ini dapat membantu usaha menjadi lebih tertata dan berkembang.",
    "legalitas_dimiliki": [
      "NIB"
    ],
    "legalitas_belum": [
      "Merek Dagang",
      "NPWP",
      "PIRT"
    ],
    "legalitas_status": "sebagian",
    "kategori": "Kuliner",
    "lingkungan": "Lingkungan 2",
    "tahun_berdiri_num": 2026,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Kedai+Ameera+Majjelling+Wattang+Sidrap",
    "omzet_display": "Rp1.000.000 – Rp5.000.000",
    "omzet_kategori": "Rp1.000.000 – Rp5.000.000"
  },
  {
    "nama_usaha": "Rumah Makan Sinar Agung",
    "pemilik": "Hj. Salmiati",
    "gender": "Perempuan",
    "alamat": "Jl. Jendral Sudirman, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan",
    "maps": "RM. Prasmanan Sinar Agung",
    "jenis_usaha": "Kuliner",
    "produk": "Ikan Bakar, Ayam Bakar, dan Prasmanan",
    "tahun_berdiri": "2000",
    "tenaga_kerja": "2–5 orang",
    "omzet": "Rp1.000.000–Rp5.000.000",
    "legalitas_narasi": "Berdasarkan data yang tercantum, usaha ini telah memiliki NIB dan NPWP. Sertifikat halal, PIRT, dan merek dagang masih belum dicantumkan. Kondisi ini menunjukkan legalitas usaha sudah berjalan, tetapi belum sepenuhnya lengkap.",
    "pemasaran_narasi": "Penjualan dilakukan melalui toko dan dari rumah. Media digital yang digunakan adalah WhatsApp. Ini menunjukkan usaha masih mengandalkan pemasaran langsung dengan dukungan komunikasi digital sederhana.",
    "kondisi_narasi": "Kendala utama yang dihadapi meliputi modal, pemasaran, dan legalitas. Untuk pengembangan usaha, dibutuhkan bantuan permodalan. Kebutuhan ini penting agar usaha dapat menjaga operasional dan meningkatkan kapasitas usahanya.",
    "legalitas_dimiliki": [
      "NIB",
      "NPWP"
    ],
    "legalitas_belum": [
      "Merek Dagang",
      "PIRT",
      "Sertifikat Halal"
    ],
    "legalitas_status": "sebagian",
    "kategori": "Kuliner",
    "lingkungan": "Lingkungan 1",
    "tahun_berdiri_num": 2000,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=RM.+Prasmanan+Sinar+Agung+Majjelling+Wattang+Sidrap",
    "omzet_display": "Rp1.000.000 – Rp5.000.000",
    "omzet_kategori": "Rp1.000.000 – Rp5.000.000"
  },
  {
    "nama_usaha": "Kedai 33",
    "pemilik": "Faisal",
    "gender": "Laki-laki",
    "alamat": "Jl. Jendral Sudirman, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan",
    "maps": "-",
    "jenis_usaha": "Kuliner",
    "produk": "Gado-Gado, Sokko Begadang, Nasi Pecel",
    "tahun_berdiri": "2026",
    "tenaga_kerja": "2–5 orang",
    "omzet": "kurang dari Rp1.000.000",
    "legalitas_narasi": "Usaha ini telah memiliki NIB dan sertifikat halal. Namun, PIRT, Merek dagang, dan NPWP belum tampak lengkap pada data. Secara umum, legalitasnya masih perlu dilengkapi agar lebih kuat secara administratif.",
    "pemasaran_narasi": "Penjualan dilakukan melalui toko, dari rumah, dan online. Media digital yang digunakan adalah WhatsApp. Pola ini menunjukkan usaha sudah memakai jalur online, tetapi masih sederhana.",
    "kondisi_narasi": "Kendala utama yang dihadapi adalah modal, pemasaran, peralatan produksi, dan bahan baku gas. Untuk pengembangan usaha, dibutuhkan bantuan permodalan. Dukungan ini penting agar usaha lebih stabil dalam operasional harian.",
    "legalitas_dimiliki": [
      "NIB",
      "Sertifikat Halal"
    ],
    "legalitas_belum": [
      "Merek Dagang",
      "NPWP",
      "PIRT"
    ],
    "legalitas_status": "sebagian",
    "kategori": "Kuliner",
    "lingkungan": "Lingkungan 1",
    "tahun_berdiri_num": 2026,
    "maps_url": "https://maps.app.goo.gl/qvPbrLNH2Swi2RCg7?g_st=ac",
    "omzet_display": "kurang dari Rp1.000.000",
    "omzet_kategori": "< Rp1.000.000"
  },
  {
    "nama_usaha": "Shangcoffee.idn",
    "pemilik": "Fahri Putra Wijaya",
    "gender": "Laki-laki",
    "alamat": "Jl. Jend. Sudirman, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan",
    "maps": "Shangcoffee",
    "jenis_usaha": "Kedai kopi",
    "produk": "Coffee & Non-Coffe",
    "tahun_berdiri": "2026",
    "tenaga_kerja": "1 orang",
    "omzet": "Rp1.000.000–Rp5.000.000",
    "legalitas_narasi": "Data menunjukkan NIB, sertifikat halal, PIRT, merek dagang, dan NPWP belum dicantumkan sebagai lengkap. Karena itu, legalitas usaha masih menjadi salah satu fokus yang perlu diperhatikan.",
    "pemasaran_narasi": "Penjualan dilakukan di toko, dari rumah, online, dan melalui Grab. Media digital yang digunakan adalah Instagram. Kombinasi ini menunjukkan usaha cukup aktif memanfaatkan kanal digital dan layanan antar.",
    "kondisi_narasi": "Kendala utama yang dihadapi adalah pemasaran, legalitas, dan hambatan lokasi karena mobil truk menghalangi kedai. Untuk pengembangan usaha, dibutuhkan pelatihan digital marketing, bantuan permodalan, dan pendampingan media sosial. Kebutuhan ini sesuai dengan tantangan operasional dan promosi yang mereka hadapi.",
    "legalitas_dimiliki": [],
    "legalitas_belum": [
      "Merek Dagang",
      "NIB",
      "NPWP",
      "PIRT",
      "Sertifikat Halal"
    ],
    "legalitas_status": "belum",
    "kategori": "Kuliner",
    "lingkungan": "Lingkungan 1",
    "tahun_berdiri_num": 2026,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Shangcoffee+Majjelling+Wattang+Sidrap",
    "omzet_display": "Rp1.000.000 – Rp5.000.000",
    "omzet_kategori": "Rp1.000.000 – Rp5.000.000"
  },
  {
    "nama_usaha": "Smoothies Sultan",
    "foto": "assets/foto17.jpg",
    "pemilik": "Nurhana",
    "gender": "Perempuan",
    "alamat": "Jl. Jend. Sudirman, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan",
    "maps": "-",
    "jenis_usaha": "Jajanan",
    "produk": "Aneka Makanan dan Minuman",
    "tahun_berdiri": "2024",
    "tenaga_kerja": "1 orang",
    "omzet": "Rp5.000.000–Rp10.000.000",
    "legalitas_narasi": "Berdasarkan hasil pendataan, usaha Smoothis Sultan belum memiliki legalitas usaha yang lengkap, seperti Nomor Induk Berusaha (NIB), Sertifikat Halal, PIRT, Merek Dagang, maupun NPWP. Kondisi ini menunjukkan bahwa usaha masih memiliki peluang untuk meningkatkan aspek administrasi dan legalitas sebagai upaya memperkuat daya saing. Dengan adanya pendampingan dalam pengurusan legalitas melalui OSS dan program sertifikasi halal, usaha ini diharapkan dapat berkembang lebih baik serta meningkatkan kepercayaan konsumen. - Pemasaran Smoothis Sultan memasarkan produknya secara langsung melalui toko atau rumah sekaligus memanfaatkan penjualan secara online. Dalam kegiatan promosi, pelaku usaha telah menggunakan berbagai media digital seperti WhatsApp, Facebook, dan Instagram sebagai sarana komunikasi dengan pelanggan. Pemanfaatan beberapa platform tersebut menunjukkan bahwa usaha ini telah mulai beradaptasi dengan perkembangan pemasaran digital sehingga mampu menjangkau konsumen yang lebih luas.",
    "pemasaran_narasi": "Smoothis Sultan memasarkan produknya secara langsung melalui toko atau rumah sekaligus memanfaatkan penjualan secara online. Dalam kegiatan promosi, pelaku usaha telah menggunakan berbagai media digital seperti WhatsApp, Facebook, dan Instagram sebagai sarana komunikasi dengan pelanggan. Pemanfaatan beberapa platform tersebut menunjukkan bahwa usaha ini telah mulai beradaptasi dengan perkembangan pemasaran digital sehingga mampu menjangkau konsumen yang lebih luas.",
    "kondisi_narasi": "Kendala utama yang dihadapi tidak ada. Namun, kebutuhan pengembangan usaha masih berupa pendampingan OSS/NIB dan sertifikasi halal.",
    "legalitas_dimiliki": [],
    "legalitas_belum": [
      "Merek Dagang",
      "NIB",
      "NPWP",
      "PIRT",
      "Sertifikat Halal"
    ],
    "legalitas_status": "belum",
    "kategori": "Kuliner",
    "lingkungan": "Lingkungan 2",
    "tahun_berdiri_num": 2024,
    "maps_url": "https://maps.app.goo.gl/ZUjmn1MEBvHBDQKY8?g_st=ac",
    "omzet_display": "Rp5.000.000 – Rp10.000.000",
    "omzet_kategori": "Rp5.000.000 – Rp10.000.000"
  },
  {
    "nama_usaha": "Toko Anugrah",
    "pemilik": "Hj. Jumiati",
    "gender": "Perempuan",
    "alamat": "Jl. Veteran, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan",
    "maps": "-",
    "jenis_usaha": "Perdagangan",
    "produk": "Campuran",
    "tahun_berdiri": "1993",
    "tenaga_kerja": "1 orang",
    "omzet": "Rp1.000.000–Rp5.000.000",
    "legalitas_narasi": "Toko Anugrah belum memiliki NIB dan NPWP sehingga legalitas usahanya masih perlu dilengkapi untuk mendukung pengembangan usaha. - Pemasaran Penjualan dilakukan melalui toko/rumah dan belum memanfaatkan media digital sehingga pemasaran masih berfokus pada pelanggan sekitar. - Kondisi dan Pengembangan Usaha Pemilik usaha menyampaikan bahwa saat ini tidak terdapat kendala yang menghambat kegiatan usaha dan belum memiliki kebutuhan pengembangan usaha secara khusus. Meskipun demikian, peningkatan kapasitas usaha melalui digitalisasi pemasaran maupun pengurusan legalitas tetap menjadi peluang yang dapat dipertimbangkan guna mendukung perkembangan usaha di masa depan.",
    "pemasaran_narasi": "Penjualan dilakukan melalui toko/rumah dan belum memanfaatkan media digital sehingga pemasaran masih berfokus pada pelanggan sekitar. - Kondisi dan Pengembangan Usaha Pemilik usaha menyampaikan bahwa saat ini tidak terdapat kendala yang menghambat kegiatan usaha dan belum memiliki kebutuhan pengembangan usaha secara khusus. Meskipun demikian, peningkatan kapasitas usaha melalui digitalisasi pemasaran maupun pengurusan legalitas tetap menjadi peluang yang dapat dipertimbangkan guna mendukung perkembangan usaha di masa depan.",
    "kondisi_narasi": "Pemilik usaha menyampaikan bahwa saat ini tidak terdapat kendala yang menghambat kegiatan usaha dan belum memiliki kebutuhan pengembangan usaha secara khusus. Meskipun demikian, peningkatan kapasitas usaha melalui digitalisasi pemasaran maupun pengurusan legalitas tetap menjadi peluang yang dapat dipertimbangkan guna mendukung perkembangan usaha di masa depan.",
    "legalitas_dimiliki": [],
    "legalitas_belum": [
      "NIB",
      "NPWP"
    ],
    "legalitas_status": "belum",
    "kategori": "Perdagangan",
    "lingkungan": "Lingkungan 1",
    "tahun_berdiri_num": 1993,
    "maps_url": "https://maps.app.goo.gl/MCpYi6YUthB1RJA7A?g_st=ac",
    "omzet_display": "Rp1.000.000 – Rp5.000.000",
    "omzet_kategori": "Rp1.000.000 – Rp5.000.000"
  },
  {
    "nama_usaha": "Toko Uwaisyah",
    "pemilik": "Ismayana",
    "gender": "Perempuan",
    "alamat": "Jl. Veteran, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan",
    "maps": "-",
    "jenis_usaha": "Perdagangan",
    "produk": "Campuran",
    "tahun_berdiri": "2025",
    "tenaga_kerja": "2–5 orang",
    "omzet": "Rp1.000.000–Rp5.000.000",
    "legalitas_narasi": "Berdasarkan hasil pendataan, Toko Uwaisya belum memiliki legalitas usaha berupa Nomor Induk Berusaha (NIB) dan NPWP. Oleh karena itu, diperlukan pendampingan dalam proses pengurusan legalitas agar usaha memiliki perlindungan hukum sekaligus meningkatkan kredibilitas di mata konsumen. Legalitas tersebut juga akan mempermudah pelaku usaha dalam mengakses berbagai program pemerintah bagi UMKM. - Pemasaran Kegiatan penjualan dilakukan secara langsung melalui toko atau rumah dan hingga saat ini belum memanfaatkan media digital sebagai sarana pemasaran. Sistem pemasaran masih berfokus pada konsumen sekitar lingkungan usaha. Penggunaan media sosial maupun marketplace menjadi peluang yang dapat dimanfaatkan untuk meningkatkan jangkauan pasar. - Kondisi dan Pengembangan Usaha Kendala utama yang dihadapi pelaku usaha adalah keterbatasan permodalan yang memengaruhi pengembangan usaha. Oleh sebab itu, kebutuhan utama yang disampaikan adalah pendampingan dalam pengurusan OSS/NIB agar usaha memiliki legalitas yang lebih baik. Dengan dukungan tersebut, usaha diharapkan dapat berkembang secara berkelanjutan dan memiliki akses yang lebih luas terhadap berbagai program pemberdayaan UMKM.",
    "pemasaran_narasi": "Kegiatan penjualan dilakukan secara langsung melalui toko atau rumah dan hingga saat ini belum memanfaatkan media digital sebagai sarana pemasaran. Sistem pemasaran masih berfokus pada konsumen sekitar lingkungan usaha. Penggunaan media sosial maupun marketplace menjadi peluang yang dapat dimanfaatkan untuk meningkatkan jangkauan pasar. - Kondisi dan Pengembangan Usaha Kendala utama yang dihadapi pelaku usaha adalah keterbatasan permodalan yang memengaruhi pengembangan usaha. Oleh sebab itu, kebutuhan utama yang disampaikan adalah pendampingan dalam pengurusan OSS/NIB agar usaha memiliki legalitas yang lebih baik. Dengan dukungan tersebut, usaha diharapkan dapat berkembang secara berkelanjutan dan memiliki akses yang lebih luas terhadap berbagai program pemberdayaan UMKM.",
    "kondisi_narasi": "Kendala utama yang dihadapi pelaku usaha adalah keterbatasan permodalan yang memengaruhi pengembangan usaha. Oleh sebab itu, kebutuhan utama yang disampaikan adalah pendampingan dalam pengurusan OSS/NIB agar usaha memiliki legalitas yang lebih baik. Dengan dukungan tersebut, usaha diharapkan dapat berkembang secara berkelanjutan dan memiliki akses yang lebih luas terhadap berbagai program pemberdayaan UMKM.",
    "legalitas_dimiliki": [
      "NIB"
    ],
    "legalitas_belum": [
      "NPWP"
    ],
    "legalitas_status": "sebagian",
    "kategori": "Perdagangan",
    "lingkungan": "Lingkungan 1",
    "tahun_berdiri_num": 2025,
    "maps_url": "https://maps.app.goo.gl/szGFPFMVEHmWmbCR7?g_st=ac",
    "omzet_display": "Rp1.000.000 – Rp5.000.000",
    "omzet_kategori": "Rp1.000.000 – Rp5.000.000"
  },
  {
    "nama_usaha": "Toko Husna",
    "pemilik": "Husna",
    "gender": "Perempuan",
    "alamat": "Jl. Jend. Sudirman, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan",
    "maps": "-",
    "jenis_usaha": "Perdagangan",
    "produk": "Campuran",
    "tahun_berdiri": "2002",
    "tenaga_kerja": "2 orang",
    "omzet": "< Rp1.000.000",
    "legalitas_narasi": "Toko Husna belum memiliki legalitas usaha berupa NIB dan NPWP berdasarkan hasil pendataan. Kondisi tersebut menunjukkan bahwa masih terdapat ruang untuk melengkapi dokumen administrasi usaha agar sesuai dengan ketentuan yang berlaku. Kepemilikan legalitas diharapkan dapat meningkatkan kepercayaan konsumen sekaligus mendukung pengembangan usaha ke depan. - Pemasaran Penjualan produk dilakukan secara langsung melalui toko atau rumah dan belum memanfaatkan media digital sebagai media promosi. Aktivitas pemasaran masih bergantung pada pelanggan sekitar serta pembeli yang datang langsung ke lokasi usaha. Penggunaan platform digital menjadi salah satu peluang yang dapat dimanfaatkan untuk memperluas jangkauan pemasaran. - Kondisi dan Pengembangan Usaha Pelaku usaha menyampaikan bahwa tidak terdapat kendala yang berarti dalam menjalankan usahanya. Namun demikian, usaha masih membutuhkan pendampingan dalam pengurusan OSS/NIB sebagai upaya melengkapi legalitas usaha. Langkah tersebut diharapkan dapat mendukung pengembangan usaha secara lebih profesional.",
    "pemasaran_narasi": "Penjualan produk dilakukan secara langsung melalui toko atau rumah dan belum memanfaatkan media digital sebagai media promosi. Aktivitas pemasaran masih bergantung pada pelanggan sekitar serta pembeli yang datang langsung ke lokasi usaha. Penggunaan platform digital menjadi salah satu peluang yang dapat dimanfaatkan untuk memperluas jangkauan pemasaran. - Kondisi dan Pengembangan Usaha Pelaku usaha menyampaikan bahwa tidak terdapat kendala yang berarti dalam menjalankan usahanya. Namun demikian, usaha masih membutuhkan pendampingan dalam pengurusan OSS/NIB sebagai upaya melengkapi legalitas usaha. Langkah tersebut diharapkan dapat mendukung pengembangan usaha secara lebih profesional.",
    "kondisi_narasi": "Pelaku usaha menyampaikan bahwa tidak terdapat kendala yang berarti dalam menjalankan usahanya. Namun demikian, usaha masih membutuhkan pendampingan dalam pengurusan OSS/NIB sebagai upaya melengkapi legalitas usaha. Langkah tersebut diharapkan dapat mendukung pengembangan usaha secara lebih profesional.",
    "legalitas_dimiliki": [],
    "legalitas_belum": [
      "NIB",
      "NPWP"
    ],
    "legalitas_status": "belum",
    "kategori": "Perdagangan",
    "lingkungan": "Lingkungan 1",
    "tahun_berdiri_num": 2002,
    "maps_url": "https://maps.app.goo.gl/4BcJaPJZHg1ndCSE7?g_st=ac",
    "omzet_display": "< Rp1.000.000",
    "omzet_kategori": "< Rp1.000.000"
  },
  {
    "nama_usaha": "Toko Nabila",
    "pemilik": "Hj. Pahima",
    "gender": "Perempuan",
    "alamat": "Jl. Jend. Sudirman, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan",
    "maps": "Toko Nabila",
    "jenis_usaha": "Perdagangan",
    "produk": "Campuran",
    "tahun_berdiri": "2022",
    "tenaga_kerja": "2–5 orang",
    "omzet": "Rp1.000.000–Rp5.000.000",
    "legalitas_narasi": "Berdasarkan hasil pendataan, Toko Nabila belum memiliki legalitas usaha berupa NIB dan NPWP. Kondisi ini menunjukkan bahwa aspek administrasi usaha masih perlu dilengkapi agar usaha memiliki dasar hukum yang lebih kuat. Legalitas tersebut juga akan memberikan manfaat dalam mendukung pengembangan usaha di masa mendatang. - Pemasaran Kegiatan pemasaran dilakukan melalui toko atau rumah tanpa memanfaatkan media digital. Penjualan masih mengandalkan pelanggan sekitar dan hubungan langsung dengan konsumen. Ke depan, pemanfaatan media sosial dapat menjadi alternatif untuk meningkatkan promosi dan memperluas pasar. - Kondisi dan Pengembangan Usaha Pemilik usaha menyampaikan bahwa tidak terdapat kendala yang dihadapi dalam menjalankan usaha maupun kebutuhan pengembangan usaha tertentu. Meskipun demikian, peningkatan legalitas dan pemanfaatan pemasaran digital tetap dapat menjadi peluang untuk mendukung keberlanjutan usaha.",
    "pemasaran_narasi": "Kegiatan pemasaran dilakukan melalui toko atau rumah tanpa memanfaatkan media digital. Penjualan masih mengandalkan pelanggan sekitar dan hubungan langsung dengan konsumen. Ke depan, pemanfaatan media sosial dapat menjadi alternatif untuk meningkatkan promosi dan memperluas pasar. - Kondisi dan Pengembangan Usaha Pemilik usaha menyampaikan bahwa tidak terdapat kendala yang dihadapi dalam menjalankan usaha maupun kebutuhan pengembangan usaha tertentu. Meskipun demikian, peningkatan legalitas dan pemanfaatan pemasaran digital tetap dapat menjadi peluang untuk mendukung keberlanjutan usaha.",
    "kondisi_narasi": "Pemilik usaha menyampaikan bahwa tidak terdapat kendala yang dihadapi dalam menjalankan usaha maupun kebutuhan pengembangan usaha tertentu. Meskipun demikian, peningkatan legalitas dan pemanfaatan pemasaran digital tetap dapat menjadi peluang untuk mendukung keberlanjutan usaha.",
    "legalitas_dimiliki": [],
    "legalitas_belum": [
      "NIB",
      "NPWP"
    ],
    "legalitas_status": "belum",
    "kategori": "Perdagangan",
    "lingkungan": "Lingkungan 1",
    "tahun_berdiri_num": 2022,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Toko+Nabila+Majjelling+Wattang+Sidrap",
    "omzet_display": "Rp1.000.000 – Rp5.000.000",
    "omzet_kategori": "Rp1.000.000 – Rp5.000.000"
  },
  {
    "nama_usaha": "Toko Mirza",
    "pemilik": "Hj. Asma",
    "gender": "Perempuan",
    "alamat": "Jl. Jend. Sudirman, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan",
    "maps": "-",
    "jenis_usaha": "Perdagangan",
    "produk": "Campuran",
    "tahun_berdiri": "2026",
    "tenaga_kerja": "2–5 orang",
    "omzet": "Rp1.000.000–Rp5.000.000",
    "legalitas_narasi": "Toko Mirza belum memiliki legalitas usaha berupa Nomor Induk Berusaha (NIB) maupun Nomor Pokok Wajib Pajak (NPWP). Kondisi tersebut menunjukkan bahwa administrasi usaha masih perlu dilengkapi agar memiliki dasar hukum yang lebih kuat dalam menjalankan kegiatan usaha. - Pemasaran Kegiatan pemasaran Toko Mirza masih dilakukan secara langsung melalui toko atau rumah. Hingga saat ini usaha belum memanfaatkan media digital sebagai sarana promosi maupun penjualan sehingga sebagian besar konsumen berasal dari lingkungan sekitar dan pelanggan tetap. Ke depan, pemanfaatan media sosial maupun platform digital dapat menjadi alternatif untuk memperluas jangkauan pasar serta meningkatkan daya saing usaha. - Kondisi dan Pengembangan Usaha Pemilik usaha menyampaikan bahwa selama menjalankan usaha tidak terdapat kendala yang berarti dan belum memiliki kebutuhan pengembangan usaha secara khusus. Meskipun demikian, peningkatan legalitas usaha dan pengenalan strategi pemasaran digital tetap menjadi peluang yang dapat mendukung perkembangan usaha agar lebih kompetitif di masa mendatang.",
    "pemasaran_narasi": "Kegiatan pemasaran Toko Mirza masih dilakukan secara langsung melalui toko atau rumah. Hingga saat ini usaha belum memanfaatkan media digital sebagai sarana promosi maupun penjualan sehingga sebagian besar konsumen berasal dari lingkungan sekitar dan pelanggan tetap. Ke depan, pemanfaatan media sosial maupun platform digital dapat menjadi alternatif untuk memperluas jangkauan pasar serta meningkatkan daya saing usaha. - Kondisi dan Pengembangan Usaha Pemilik usaha menyampaikan bahwa selama menjalankan usaha tidak terdapat kendala yang berarti dan belum memiliki kebutuhan pengembangan usaha secara khusus. Meskipun demikian, peningkatan legalitas usaha dan pengenalan strategi pemasaran digital tetap menjadi peluang yang dapat mendukung perkembangan usaha agar lebih kompetitif di masa mendatang.",
    "kondisi_narasi": "Pemilik usaha menyampaikan bahwa selama menjalankan usaha tidak terdapat kendala yang berarti dan belum memiliki kebutuhan pengembangan usaha secara khusus. Meskipun demikian, peningkatan legalitas usaha dan pengenalan strategi pemasaran digital tetap menjadi peluang yang dapat mendukung perkembangan usaha agar lebih kompetitif di masa mendatang.",
    "legalitas_dimiliki": [],
    "legalitas_belum": [
      "NIB",
      "NPWP"
    ],
    "legalitas_status": "belum",
    "kategori": "Perdagangan",
    "lingkungan": "Lingkungan 1",
    "tahun_berdiri_num": 2026,
    "maps_url": "https://maps.app.goo.gl/2Sq6v3p2Vi8yzgnS6?g_st=ac",
    "omzet_display": "Rp1.000.000 – Rp5.000.000",
    "omzet_kategori": "Rp1.000.000 – Rp5.000.000"
  },
  {
    "nama_usaha": "Toko Diana",
    "pemilik": "Mardiana",
    "gender": "Perempuan",
    "alamat": "Jl. Jend. Sudirman, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan",
    "maps": "-",
    "jenis_usaha": "Perdagangan",
    "produk": "Campuran",
    "tahun_berdiri": "2008",
    "tenaga_kerja": "2–5 orang",
    "omzet": "Rp1.000.000–Rp5.000.000",
    "legalitas_narasi": "Hasil pendataan menunjukkan bahwa Toko Diana belum memiliki legalitas usaha berupa NIB dan NPWP. Hal ini mengindikasikan bahwa masih terdapat kesempatan untuk melengkapi dokumen administrasi usaha agar sesuai dengan ketentuan yang berlaku. Kepemilikan legalitas usaha diharapkan dapat meningkatkan kepercayaan konsumen serta mempermudah akses terhadap berbagai program pengembangan UMKM dari pemerintah. - Pemasaran Penjualan produk dilakukan secara langsung melalui toko atau rumah dengan mengandalkan pelanggan yang datang ke lokasi usaha. Sampai saat ini Toko Diana belum menggunakan media digital sebagai sarana promosi maupun pemasaran. Oleh karena itu, pemanfaatan media sosial dan platform digital dapat menjadi langkah yang potensial untuk memperluas jangkauan konsumen dan meningkatkan penjualan - Kondisi dan Pengembangan Usaha Pemilik usaha tidak mengalami kendala yang berarti dalam menjalankan usahanya dan belum memiliki kebutuhan pengembangan usaha secara khusus. Namun demikian, peningkatan kapasitas usaha melalui digitalisasi pemasaran serta pengurusan legalitas tetap dapat menjadi langkah strategis dalam mendukung keberlanjutan usaha di masa depan",
    "pemasaran_narasi": "Penjualan produk dilakukan secara langsung melalui toko atau rumah dengan mengandalkan pelanggan yang datang ke lokasi usaha. Sampai saat ini Toko Diana belum menggunakan media digital sebagai sarana promosi maupun pemasaran. Oleh karena itu, pemanfaatan media sosial dan platform digital dapat menjadi langkah yang potensial untuk memperluas jangkauan konsumen dan meningkatkan penjualan - Kondisi dan Pengembangan Usaha Pemilik usaha tidak mengalami kendala yang berarti dalam menjalankan usahanya dan belum memiliki kebutuhan pengembangan usaha secara khusus. Namun demikian, peningkatan kapasitas usaha melalui digitalisasi pemasaran serta pengurusan legalitas tetap dapat menjadi langkah strategis dalam mendukung keberlanjutan usaha di masa depan",
    "kondisi_narasi": "Pemilik usaha tidak mengalami kendala yang berarti dalam menjalankan usahanya dan belum memiliki kebutuhan pengembangan usaha secara khusus. Namun demikian, peningkatan kapasitas usaha melalui digitalisasi pemasaran serta pengurusan legalitas tetap dapat menjadi langkah strategis dalam mendukung keberlanjutan usaha di masa depan",
    "legalitas_dimiliki": [],
    "legalitas_belum": [
      "NIB",
      "NPWP"
    ],
    "legalitas_status": "belum",
    "kategori": "Perdagangan",
    "lingkungan": "Lingkungan 2",
    "tahun_berdiri_num": 2008,
    "maps_url": "https://maps.app.goo.gl/XZFpTSYSE41oEng16?g_st=ac",
    "omzet_display": "Rp1.000.000 – Rp5.000.000",
    "omzet_kategori": "Rp1.000.000 – Rp5.000.000"
  },
  {
    "nama_usaha": "Toko Aliqa",
    "pemilik": "Saprida",
    "gender": "Perempuan",
    "alamat": "Jl. Jend. Sudirman, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan",
    "maps": "-",
    "jenis_usaha": "Perdagangan",
    "produk": "Campuran",
    "tahun_berdiri": "2024",
    "tenaga_kerja": "2–5 orang",
    "omzet": "Rp1.000.000–Rp5.000.000",
    "legalitas_narasi": "Berdasarkan hasil pendataan, Toko Aliqa belum memiliki legalitas usaha berupa Nomor Induk Berusaha (NIB) maupun NPWP. Kondisi tersebut menunjukkan bahwa legalitas usaha masih perlu dilengkapi sebagai bentuk kepatuhan terhadap regulasi yang berlaku. Kepemilikan dokumen legalitas diharapkan dapat memberikan perlindungan hukum sekaligus membuka peluang bagi pelaku usaha untuk memperoleh berbagai bentuk pembinaan dan pengembangan usah. - Pemasaran Kegiatan pemasaran masih dilakukan secara konvensional melalui toko atau rumah tanpa memanfaatkan media digital sebagai media promosi. Penjualan lebih banyak bergantung pada pelanggan tetap dan masyarakat sekitar. Penggunaan media sosial maupun marketplace di masa mendatang diharapkan dapat membantu memperluas jaringan pemasaran dan meningkatkan daya saing usaha. - Kondisi dan Pengembangan Usaha Selama menjalankan usaha, pemilik menyampaikan bahwa tidak terdapat kendala yang menghambat kegiatan operasional dan belum memiliki kebutuhan pengembangan usaha secara khusus. Walaupun demikian, peningkatan legalitas usaha dan penguatan strategi pemasaran berbasis digital tetap menjadi peluang yang dapat mendukung perkembangan usaha secara berkelanjutan.",
    "pemasaran_narasi": "Kegiatan pemasaran masih dilakukan secara konvensional melalui toko atau rumah tanpa memanfaatkan media digital sebagai media promosi. Penjualan lebih banyak bergantung pada pelanggan tetap dan masyarakat sekitar. Penggunaan media sosial maupun marketplace di masa mendatang diharapkan dapat membantu memperluas jaringan pemasaran dan meningkatkan daya saing usaha. - Kondisi dan Pengembangan Usaha Selama menjalankan usaha, pemilik menyampaikan bahwa tidak terdapat kendala yang menghambat kegiatan operasional dan belum memiliki kebutuhan pengembangan usaha secara khusus. Walaupun demikian, peningkatan legalitas usaha dan penguatan strategi pemasaran berbasis digital tetap menjadi peluang yang dapat mendukung perkembangan usaha secara berkelanjutan.",
    "kondisi_narasi": "Selama menjalankan usaha, pemilik menyampaikan bahwa tidak terdapat kendala yang menghambat kegiatan operasional dan belum memiliki kebutuhan pengembangan usaha secara khusus. Walaupun demikian, peningkatan legalitas usaha dan penguatan strategi pemasaran berbasis digital tetap menjadi peluang yang dapat mendukung perkembangan usaha secara berkelanjutan.",
    "legalitas_dimiliki": [],
    "legalitas_belum": [
      "NIB",
      "NPWP"
    ],
    "legalitas_status": "belum",
    "kategori": "Perdagangan",
    "lingkungan": "Lingkungan 2",
    "tahun_berdiri_num": 2024,
    "maps_url": "https://maps.app.goo.gl/XFHvJYL6uzYkgNQv5?g_st=ac",
    "omzet_display": "Rp1.000.000 – Rp5.000.000",
    "omzet_kategori": "Rp1.000.000 – Rp5.000.000"
  },
  {
    "nama_usaha": "Toko Nur",
    "pemilik": "Asrina",
    "gender": "Perempuan",
    "alamat": "Jl. Jend. Sudirman, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan",
    "maps": "-",
    "jenis_usaha": "Perdagangan",
    "produk": "Campuran",
    "tahun_berdiri": "2024",
    "tenaga_kerja": "2–5 orang",
    "omzet": "Rp1.000.000–Rp5.000.000",
    "legalitas_narasi": "Hasil pendataan menunjukkan bahwa Toko Nur belum memiliki legalitas usaha berupa NIB maupun NPWP. Oleh sebab itu, masih diperlukan pendampingan dalam proses pengurusan legalitas agar usaha memiliki administrasi yang lebih lengkap dan sesuai dengan ketentuan yang berlaku. Legalitas usaha juga menjadi salah satu faktor penting dalam meningkatkan kredibilitas usaha serta memperluas kesempatan memperoleh dukungan dari berbagai program pemerintah. - Pemasaran Penjualan produk dilakukan secara langsung melalui toko atau rumah dan belum memanfaatkan media digital sebagai media pemasaran. Sistem pemasaran yang diterapkan masih berfokus pada pelanggan sekitar lingkungan usaha. Ke depan, pemanfaatan media sosial maupun platform digital dapat menjadi alternatif yang efektif untuk meningkatkan promosi serta menjangkau konsumen yang lebih luas. - Kondisi dan Pengembangan Usaha Pemilik usaha menyampaikan bahwa tidak terdapat kendala utama yang dihadapi dalam menjalankan usahanya serta belum memiliki kebutuhan pengembangan usaha secara khusus. Meskipun demikian, peningkatan legalitas usaha dan pemanfaatan teknologi digital dalam pemasaran tetap dapat menjadi langkah yang mendukung pertumbuhan usaha di masa mendatang.",
    "pemasaran_narasi": "Penjualan produk dilakukan secara langsung melalui toko atau rumah dan belum memanfaatkan media digital sebagai media pemasaran. Sistem pemasaran yang diterapkan masih berfokus pada pelanggan sekitar lingkungan usaha. Ke depan, pemanfaatan media sosial maupun platform digital dapat menjadi alternatif yang efektif untuk meningkatkan promosi serta menjangkau konsumen yang lebih luas. - Kondisi dan Pengembangan Usaha Pemilik usaha menyampaikan bahwa tidak terdapat kendala utama yang dihadapi dalam menjalankan usahanya serta belum memiliki kebutuhan pengembangan usaha secara khusus. Meskipun demikian, peningkatan legalitas usaha dan pemanfaatan teknologi digital dalam pemasaran tetap dapat menjadi langkah yang mendukung pertumbuhan usaha di masa mendatang.",
    "kondisi_narasi": "Pemilik usaha menyampaikan bahwa tidak terdapat kendala utama yang dihadapi dalam menjalankan usahanya serta belum memiliki kebutuhan pengembangan usaha secara khusus. Meskipun demikian, peningkatan legalitas usaha dan pemanfaatan teknologi digital dalam pemasaran tetap dapat menjadi langkah yang mendukung pertumbuhan usaha di masa mendatang.",
    "legalitas_dimiliki": [],
    "legalitas_belum": [
      "NIB",
      "NPWP"
    ],
    "legalitas_status": "belum",
    "kategori": "Perdagangan",
    "lingkungan": "Lingkungan 1",
    "tahun_berdiri_num": 2024,
    "maps_url": "https://maps.app.goo.gl/D2BeGU3W5fVgry9G9?g_st=ac",
    "omzet_display": "Rp1.000.000 – Rp5.000.000",
    "omzet_kategori": "Rp1.000.000 – Rp5.000.000"
  },
  {
    "nama_usaha": "Toko Aprilia",
    "pemilik": "Samriani",
    "gender": "Perempuan",
    "alamat": "Jl. Anggrek, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan",
    "maps": "-",
    "jenis_usaha": "Perdagangan",
    "produk": "Campuran",
    "tahun_berdiri": "2020",
    "tenaga_kerja": "2–5 orang",
    "omzet": "< Rp1.000.000",
    "legalitas_narasi": "Berdasarkan hasil pendataan, Toko Aprilia belum memiliki legalitas usaha berupa Nomor Induk Berusaha (NIB) dan NPWP. Kondisi tersebut menunjukkan bahwa aspek administrasi usaha masih perlu dilengkapi agar memiliki legalitas yang sesuai dengan ketentuan pemerintah. Kepemilikan legalitas diharapkan mampu meningkatkan kepercayaan konsumen serta memberikan kemudahan dalam mengakses berbagai program pembinaan dan pemberdayaan UMKM. - Pemasaran Aktivitas penjualan dilakukan secara langsung melalui toko atau rumah dengan melayani konsumen di sekitar lokasi usaha. Hingga saat ini usaha belum memanfaatkan media digital sebagai sarana promosi maupun penjualan sehingga pemasaran masih bersifat konvensional. Pengembangan pemasaran berbasis digital dapat menjadi peluang untuk memperluas pasar dan meningkatkan daya saing usaha di masa yang akan datang - Kondisi dan Pengembangan Usaha Selama menjalankan usahanya, pemilik Toko Aprilia menyampaikan bahwa tidak terdapat kendala yang berarti dan belum memiliki kebutuhan pengembangan usaha secara khusus. Walaupun demikian, peningkatan legalitas usaha, penguatan promosi digital, serta peningkatan kapasitas pengelolaan usaha dapat menjadi langkah strategis untuk mendukung pertumbuhan usaha secara berkelanjutan di masa mendatang.",
    "pemasaran_narasi": "Aktivitas penjualan dilakukan secara langsung melalui toko atau rumah dengan melayani konsumen di sekitar lokasi usaha. Hingga saat ini usaha belum memanfaatkan media digital sebagai sarana promosi maupun penjualan sehingga pemasaran masih bersifat konvensional. Pengembangan pemasaran berbasis digital dapat menjadi peluang untuk memperluas pasar dan meningkatkan daya saing usaha di masa yang akan datang - Kondisi dan Pengembangan Usaha Selama menjalankan usahanya, pemilik Toko Aprilia menyampaikan bahwa tidak terdapat kendala yang berarti dan belum memiliki kebutuhan pengembangan usaha secara khusus. Walaupun demikian, peningkatan legalitas usaha, penguatan promosi digital, serta peningkatan kapasitas pengelolaan usaha dapat menjadi langkah strategis untuk mendukung pertumbuhan usaha secara berkelanjutan di masa mendatang.",
    "kondisi_narasi": "Selama menjalankan usahanya, pemilik Toko Aprilia menyampaikan bahwa tidak terdapat kendala yang berarti dan belum memiliki kebutuhan pengembangan usaha secara khusus. Walaupun demikian, peningkatan legalitas usaha, penguatan promosi digital, serta peningkatan kapasitas pengelolaan usaha dapat menjadi langkah strategis untuk mendukung pertumbuhan usaha secara berkelanjutan di masa mendatang.",
    "legalitas_dimiliki": [],
    "legalitas_belum": [
      "NIB",
      "NPWP"
    ],
    "legalitas_status": "belum",
    "kategori": "Perdagangan",
    "lingkungan": "Lingkungan 1",
    "tahun_berdiri_num": 2020,
    "maps_url": "https://maps.app.goo.gl/TYEvaQ5rcnUGtSPKA",
    "omzet_display": "< Rp1.000.000",
    "omzet_kategori": "< Rp1.000.000"
  },
  {
    "nama_usaha": "Es Teh Poci Outlet Nystic Elyuna",
    "pemilik": "Nolan",
    "gender": "Laki-laki",
    "alamat": "Jl. Ganggawa, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan",
    "maps": "-",
    "jenis_usaha": "Minuman",
    "produk": "Es Teh",
    "tahun_berdiri": "tidak tercantum",
    "tenaga_kerja": "6–10 orang",
    "omzet": "lebih dari Rp10.000.000",
    "legalitas_narasi": "Pada data yang terlihat, legalitas usaha belum tercantum lengkap seperti PIRT dan NPWP. Hal ini berarti aspek administratif masih perlu dilengkapi.",
    "pemasaran_narasi": "Penjualan dilakukan melalui toko dan dari rumah. Media digital yang digunakan adalah WhatsApp. Dengan omzet yang cukup tinggi, penggunaan media digital ini bisa menjadi modal untuk penguatan promosi.",
    "kondisi_narasi": "Kendala utama yang dihadapi adalah pemasaran. Untuk pengembangan usaha, dibutuhkan pelatihan digital marketing. Kebutuhan ini selaras dengan potensi usaha yang sudah memiliki skala tenaga kerja cukup besar.",
    "legalitas_dimiliki": [
      "NIB",
      "Merek Dagang",
      "Sertifikat Halal"
    ],
    "legalitas_belum": [
      "NPWP",
      "PIRT"
    ],
    "legalitas_status": "sebagian",
    "kategori": "Kuliner",
    "lingkungan": "Lingkungan 1",
    "tahun_berdiri_num": null,
    "maps_url": "https://maps.app.goo.gl/ACjMPcgUKYXQB1ES9?g_st=ac",
    "omzet_display": "lebih dari Rp10.000.000",
    "omzet_kategori": "> Rp10.000.000"
  },
  {
    "nama_usaha": "Roti Bakar Bandung",
    "pemilik": "Anti",
    "gender": "Perempuan",
    "alamat": "Jl. Jend. Sudirman, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan",
    "maps": "-",
    "jenis_usaha": "Kuliner",
    "produk": "Roti Bakar",
    "tahun_berdiri": "2022",
    "tenaga_kerja": "1 orang",
    "omzet": "Rp1.000.000–Rp5.000.000",
    "legalitas_narasi": "Berdasarkan data yang terlihat, legalitas usaha belum tercantum lengkap. Meski begitu, usaha ini tetap memiliki aktivitas operasional yang berjalan cukup baik.",
    "pemasaran_narasi": "Penjualan dilakukan melalui gerobak. Media digital yang digunakan adalah WhatsApp, Facebook, Instagram, dan Grab. Ini menunjukkan usaha sudah cukup aktif memanfaatkan berbagai kanal pemasaran.",
    "kondisi_narasi": "Kendala utama yang dihadapi tidak ada, begitu juga kebutuhan pengembangan usaha. Kondisi ini menandakan pemilik usaha merasa usahanya sudah cukup berjalan sesuai kebutuhan saat ini.",
    "legalitas_dimiliki": [],
    "legalitas_belum": [
      "NIB",
      "NPWP",
      "PIRT",
      "Sertifikat Halal",
      "Merek Dagang"
    ],
    "legalitas_status": "belum",
    "kategori": "Kuliner",
    "lingkungan": "Lingkungan 1",
    "tahun_berdiri_num": 2022,
    "maps_url": "https://maps.app.goo.gl/tTTPWSabEyZRWvWd9?g_st=ac",
    "omzet_display": "Rp1.000.000 – Rp5.000.000",
    "omzet_kategori": "Rp1.000.000 – Rp5.000.000"
  },
  {
    "nama_usaha": "Jalangkote Mawar",
    "pemilik": "Hj. Mahyani",
    "gender": "Perempuan",
    "alamat": "Jl. Mawar, Kec. Maritengngae, Kab. Sidrap, Sulawesi Selatan",
    "maps": "Jalangkote Majjelling",
    "jenis_usaha": "Kuliner",
    "produk": "Berbagai jenis gorengan",
    "tahun_berdiri": "2000",
    "tenaga_kerja": "6–10 orang",
    "omzet": "Rp1.000.000–Rp5.000.000",
    "legalitas_narasi": "Data menunjukkan NIB, sertifikat halal sudah ada, sementara NPWP menjadi dokumen yang dicantumkan dalam status belum ada. Ini berarti masih ada ruang untuk melengkapi legalitas usaha.",
    "pemasaran_narasi": "Penjualan dilakukan melalui toko atau rumah. Media digital yang digunakan adalah WhatsApp. Strategi ini menunjukkan usaha tetap bertumpu pada penjualan langsung dengan dukungan komunikasi digital sederhana.",
    "kondisi_narasi": "Kendala utama yang dihadapi tidak ada, sedangkan kebutuhan pengembangan usaha adalah pendampingan marketplace. Kebutuhan ini penting untuk memperluas jangkauan penjualan di luar pelanggan lokal.",
    "legalitas_dimiliki": [
      "NIB",
      "Sertifikat Halal"
    ],
    "legalitas_belum": [
      "NPWP"
    ],
    "legalitas_status": "sebagian",
    "kategori": "Kuliner",
    "lingkungan": "Lingkungan 1",
    "tahun_berdiri_num": 2000,
    "maps_url": "https://www.google.com/maps/search/?api=1&query=Jalangkote+Majjelling+Majjelling+Wattang+Sidrap",
    "omzet_display": "Rp1.000.000 – Rp5.000.000",
    "omzet_kategori": "Rp1.000.000 – Rp5.000.000"
  }
];
